version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: stockpulse
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../order-service/.env
    depends_on:
      - mysql

  inventory-service:
    build:
      context: ../inventory-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ../inventory-service/.env
    depends_on:
      - mysql


volumes:
  mysql_data: